on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Build
      run: dotnet build src/A10w.DocumentGeneration.Handlebars/A10w.DocumentGeneration.Handlebars.csproj --configuration Release
    - name: Test
      run: dotnet test src/A10w.DocumentGeneration.Handlebars.IntegrationTests/A10w.DocumentGeneration.Handlebars.IntegrationTests.csproj  --configuration Release --no-build --verbosity normal --logger trx --collect:"XPlat Code Coverage"